### ISSUE TITLE
Clustering features

### ISSUE THREAD

**Issue by ArkadiyD** [facebookresearch/LaMCTS#3]
In the line https://github.com/facebookresearch/LaMCTS/blob/fa76cb573788f888a8a45697eaccbbe9b4e26e8f/LA-MCTS/Classifier.py#L418 the clustering in nodes is done based on both x and f(x) though in the paper it is said that clustering is performed based on f(x). Could you please clarify, is f(x) considered as just another variable of x for clustering?

**Comment by linnanwang** [comment]
Thank you. Yes f(x) is considered, otherwise we will only split by x. Here we want to split x based on f(x), so [x f(x)] are needed. I will clarify that in the final revision. 

However, there is an improvement here. Instead of using K-mean, to label samples into two groups. We can learn a regressor R on [x, f(x)]. The split now becomes R(x) > f(x) goes to good partition, and R(x) < f(x) goes to a bad partition.

**Comment by ArkadiyD** [comment]
Thanks!
