### ISSUE TITLE
Python package

### ISSUE THREAD

**Issue by Yard1** [facebookresearch/LaMCTS#5]
Are there any plans to add setuptools scripts (or other), so that LA-MCTS and LaNAS can be packaged and installed through pip? It would greatly simplify development of projects that would like to use them as dependencies.

I would be happy to help out with this.

**Comment by richardliaw** [comment]
hey @linnanwang, I agree with this feature request - this would be really cool to include in ray tune!

(btw, @Yard1 is a maintainer of Ray's Scikit-learn integration 😄 )

**Comment by linnanwang** [comment]
Hello @richardliaw and @Yard1,

Thanks for the suggestion and I totally agree it will be great if we can make a python package. Since the code has some other stuff, e.g. NAS, I really appreciate if you can try to make it a package for the folder of LA-MCTS. Please ping me back if you will finish it, and I will update the README accordingly. Thank you.

At the moment, I'm actively interviewing for many companies, and the family also keep me quite busy. So, I won't be able to make a pip package in a short time. Thank you.

**Comment by Yard1** [comment]
I'll make a PR soon. Best of luck with the job hunt!

**Comment by Yard1** [comment]
FYI still planning to work on it, just been busier than usual. Should be good to start soon.

**Comment by Yard1** [comment]
https://github.com/facebookresearch/LaMCTS/pull/7
